# Generated by Django 4.1.7 on 2023-03-31 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Not titled sound', max_length=64)),
                ('sound', models.FileField(upload_to='files/sounds')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/covers/sounds')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Not titled album', max_length=64)),
                ('cover', models.ImageField(upload_to='images/covers/albums')),
                ('sounds', models.ManyToManyField(to='sound.sound')),
            ],
        ),
    ]
