# Generated by Django 4.1.7 on 2023-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='authors',
            field=models.ManyToManyField(to='author.author'),
        ),
    ]
