# Generated by Django 4.1.7 on 2023-04-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('sound', '0002_album_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='author',
        ),
        migrations.AddField(
            model_name='sound',
            name='authors',
            field=models.ManyToManyField(to='author.author'),
        ),
    ]
