# Generated by Django 4.1.7 on 2023-04-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0004_alter_album_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='authors',
        ),
    ]
