# Generated by Django 4.1.7 on 2023-03-31 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Not titled author', max_length=64)),
                ('description', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
    ]
