# Generated by Django 4.1.7 on 2023-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0005_remove_album_authors'),
        ('author', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='albums',
            field=models.ManyToManyField(blank=True, to='sound.album'),
        ),
    ]
